### ISSUE TITLE
Publish source jar

### ISSUE THREAD

**Issue by OlegYch** [henrikerola/scaladin#1]
Can you please publish proper source jar in vaadin maven repo? Currently Intellij's having troubles picking source from the published jar.

Thanks, Oleg.

**Comment by eugener** [comment]
I second that

**Comment by cpoile** [comment]
I just cloned the git repository into a directory and pointed IntelliJ to that. Works fine.

**Comment by eugener** [comment]
This is when scaladin is used as a library (jar artifact) using maven

**Comment by cpoile** [comment]
That's how I'm using it too. So you have to type a few extra lines, no big deal. At least until the source jar gets published.

**Comment by benhutchison** [comment]
+1. Please publish source.

**Comment by henrikerola** [comment]
This should be fixed in version 2.0.0 I uploaded to Vaadin Directory.
