### ISSUE TITLE
Set a default empty item on FieldGroup

### ISSUE THREAD

**Issue by ndarilek** [henrikerola/scaladin#13]
I have a number of hand-coded forms which map fields to string names, and a for comprehension that unwraps all the Options on submit. I create the forms like so:

```
val fields = new FieldGroup
val email = new TextField {
  caption = "Email"; required = true
}
email.validators += emailValidator
components += email
fields.bind(email, "email")
```

Unfortunately, my first attempt at this threw an NPE because no item was set. This was fixed by doing this:

```
val fields = new FieldGroup { item = Item() }
```

Would it make sense to set a default, empty item on FieldGroups so you can just map fields without always assigning the item? It would seem to make the simplest case even simpler, to make the syntax cleaner, and to be consistent with the fact that Scala users might want to code up forms without using beans or other Java silliness.

Thanks.

**Comment by henrikerola** [comment]
The idea with FieldGroup is that the item is specified explicitly.
