### ISSUE TITLE
Should Navigator.ViewChangeEvent.parameters return None instead of an empty string?

### ISSUE THREAD

**Issue by ndarilek** [henrikerola/scaladin#17]
When attempting to refactor to Navigator, I discovered that parameter checks were returning Some("") for empty strings.

This was rather surprising to me. I see that you're wrapping the property in Option which is good as it filters out null, but it makes sense to me that conceptually I would treat null and "" parameters the same.

The fix is easy--just add a .filterNot(_.isEmpty) to the line that assigns the property--but I wanted to ensure that we're on the same page before making it. As it stands, to check for empty properties, it looks like I have to check for both None and Some(""), which is annoying.

Thanks.

**Comment by henrikerola** [comment]
If parameters is never null then one option is just use String instead of Option[String].

**Comment by ndarilek** [comment]
I don't see any null checks in the Vaadin code. The Scala/null purist in me wonders if there is any chance this might be overlooked, but if the internal code isn't durable enough to handle nulls and assumes they aren't present, then no amount of Option can either.

So yeah, making them non-optional would work too.

**Comment by ndarilek** [comment]
Fixed:

https://github.com/ndarilek/scaladin

**Comment by henrikerola** [comment]
Thanks, fixed so that a null is converted to "".
