### ISSUE TITLE
Convert Vaadin validations to Scaladin

### ISSUE THREAD

**Issue by ndarilek** [henrikerola/scaladin#18]
I have the following code:

  implicit def abstractValidatorToValidator(v:com.vaadin.data.validator.AbstractValidator[_]):Validator = {
    Validator({ value =>
      try {
        v.validate(value.orNull)
        Valid
      } catch {
        case e:com.vaadin.data.Validator.InvalidValueException =>
          Invalid(List(e.getMessage))
      }
    })
  }

This lets me add Vaadin validators to Scaladin fields.

Where should I put this? I don't want to have to wrap each and every Vaadin validator, but it seems like this implicit should get picked up automatically with no extra work from the user. Perhaps it should go into the implicits object, but that feels wrong to me. Scaladin overrides the validation functionality, and its current implementation is less feature complete than Vaadin's in that it can't use any of the pre-existing validations without additional work. Seems like it should both add functionality and use Vaadin's validations with no modifications.

**Comment by ripla** [comment]
Currently we have this in the Validator companion object:

``` scala
def apply(vaadinValidator: com.vaadin.data.Validator): Validator
```

Seems this sounds like a pretty common use case, we could create a simple implicit for this.

**Comment by henrikerola** [comment]
I am not sure if we want to use a implicit for this. Writing Validator(new MyVaadinValidator) is clear what it does, I would say. Problem with implicits that it's a bit magic.

**Comment by ndarilek** [comment]
I would call replacing Vaadin validations as documented everywhere with
your non-standard implementation more magical than an implicit that
makes default validations work as your framework expects. Syntactic
sugar is nice, but not at the expense of making it impossible to use
packaged validations without knowing some Scaladin-specific magic. This
really tripped me up as someone new to Vaadin but familiar with Scala.
Suddenly the standard documentation wasn't serving me at all, and I
couldn't figure out how to validate an email address. I'm a bit worried
by how far Scaladin diverges from and breaks compatibility with standard
Vaadin, but that's a different issue entirely. :)

**Comment by ripla** [comment]
I think breaking compatibility is inevitable in the way we wrap things. The idea is that you would build your application with the provided Scala classes. If we provide some migration helpers like the Validator(new MyVaadinValidator), then those are there to help bridge the gap. So, if you want to validate something you can: a) extend the Scaladin Validator and roll your own b) wrap an existing com.vaadin validator with the Validator.apply helper.

One possibility would be to write a Migrations object that would have implicit wrappings for validators, components etc. But I agree with Henri, implicits are a bit magical even when explicitly imported.
