### ISSUE TITLE
support scala 2.10

### ISSUE THREAD

**Issue by kostaskougios** [henrikerola/scaladin#20]
Any plans to support 2.10 for scaladin 2.x ?

Is scaladin 3 a drop in replacement for 2.x?

**Comment by henrikerola** [comment]
Scaladin 2.x should work with Scala 2.10, you just need to compile your own version of it.

And Scaladin 3 is not a drop in replacement for 2.x.

**Comment by kostaskougios** [comment]
ah, such a shame, I was hoping to fetch it from the mvn central :)

Ok, will build my own, cheers.

**Comment by kostaskougios** [comment]
Btw, any plans on maintaining/updating older versions of the library to newer scala versions? I.e. now my project is stuck to scala 2.9.2 as I couldn't compile scaladin 2 with 2.10 (sbt gives me some weird errors). And also it is hard for library users to keep the library up to date.

I.e. if I adopt scaladin v3 and then scala 2.11 is released, will I be again stuck with scala 2.10?

**Comment by kostaskougios** [comment]
Hi, sorry got to ask again. Still stuck to scala 2.9.2 due to scaladin library 2.2 now been available for scala 2.10. Now I tried to compile scaladin for scala 2.10 without any luck, I don't know how to use sbt and I always get:

sbt.ResolveException: unresolved dependency: com.typesafe.sbt#sbt-scalariform;1.0.0: not found

(git clone scaladin , fresh install of sbt)

So two questions:
1. how can I compile it for 2.10?
2. for long term adoption of a library, it must be maintained and updated    as projects depending on the library will either be stuck to old versions or be forced to replace the lib with something else. Do you have an update plan for scaladin regarding new scala versions which break compatibility?

**Comment by ripla** [comment]
As for 1: I've pushed a version of Scaladin 2.2 that's seems to work with 2.10. It's in the 2.2_2.10 branch. For point 2, I think we'll always try to keep the newest version of Scaladin using the newest version of Scala. As Vaadin 6 approaches EOL, so will Scaladin 2.2.
