### ISSUE TITLE
Roadmap to 3.0 or snapshot builds

### ISSUE THREAD

**Issue by ndarilek** [henrikerola/scaladin#22]
Developing with Scaladin is somewhat challenging because I have to build the library myself and ensure that it is present in all my projects. I use Gradle for my builds, and for some reason it has issues with the artefacts produced by SBT when published to my local repository. Of course, new complexities arise when performing automated builds on CI servers which must check out their own copy of Scaladin and build that as part of the build process.

7.0 has been out for a while now, and while there are certainly rough edges in Scaladin, it'd be nice to have a 3.0 release of some kind published such that build tools can pick it up. I'm successfully using it in several Vaadin projects, so I'd definitely call it ready for use.

Would it be possible to create a 3.0 roadmap for a public 7.0-compatible release? Or could 3.0.0-SNAPSHOT be automatically built and published somewhere so I can update all of my projects to use that?

Thanks.

**Comment by henrikerola** [comment]
3.0 has been released so closing.
