### ISSUE TITLE
Youtube vid has no sound

### ISSUE THREAD

**Issue by fancellu** [henrikerola/scaladin#26]
http://www.youtube.com/watch?v=-54iGed58e0

Its your talk "Building Vaadin Applications With Pure Scala"

If you've got a working video with sound that would be lovely. Thanks.

**Comment by henrikerola** [comment]
That video is recorded by the JDD conference so I cannot do much for it. Luckily I am going to give pretty much the same talk at JavaOne SF 2013 in two weeks and I think it will be recorded: 
https://oracleus.activeevents.com/2013/connect/sessionDetail.ww?SESSION_ID=5197

**Comment by fancellu** [comment]
Thanks. Look forward to seeing it.

Dino.

**Comment by fancellu** [comment]
Did it come out yet? Can't see it anywhere.

Just started using Scaladin 3 with Vaadin 7.5, impressive. 

Thanks.
