### ISSUE TITLE
Button builder function with no click handler

### ISSUE THREAD

**Issue by hrj** [henrikerola/scaladin#3]
It would be nice to have:

```
Object Button {
  def apply (caption:String)
}
```

Useful when building quick mockups without having to worry about handling events.

**Comment by ripla** [comment]
We have `def apply(caption: String, clickListener: => Unit): Button`, but a pure caption one could be handy.

**Comment by ripla** [comment]
Fixed in 5fc84cec286d8c2f723e4ece34f2f4458e2839d1
