### ISSUE TITLE
Container.add(vaadin.ui.Component)

### ISSUE THREAD

**Issue by hrj** [henrikerola/scaladin#5]
Please provide a way to add a normal vaadin Component directly. There are components provided by addons, that can be inserted directly into the container. For example the `Refresher` addon has a `Refresher` component that can be added to a container without further configuration.

**Comment by ripla** [comment]
You'll be able to do use a provided simple wrapper to work with addons, so you can just add new components and use their Java API. Example:

``` scala
new Refresher with ScaladinWrapper
```
