### ISSUE TITLE
Cannot specify vaadin.scala.UI locale

### ISSUE THREAD

**Issue by enlait** [henrikerola/scaladin#50]
I can't find scaladin equivalent to com.vaadin.ui.UI.setLocale(..) method.

My UI locale depends on user settings, so I need to set it in init(..) method, depending on request.

**Comment by thehappycoder** [comment]
You can do it like this:

```
p.setLocale(locale)
```

In my small app I do like this in UI init:

```
val defaultLocale = new Locale("ru", "RU")
    Locale.setDefault(defaultLocale)
    p.setLocale(defaultLocale)
    ScaladinSession.current.locale = defaultLocale
```
