### ISSUE TITLE
Nightly builds of version 2.0?

### ISSUE THREAD

**Issue by xylo** [henrikerola/scaladin#6]
I would really like to test version 2.0 but could not find any nightly build.  Since there is already a build server that builds the project automatically I wonder why you don't publish the snapshot builds.  This would be very useful, especially since version 2.0 differs a lot from version 1.0.

**Comment by henrikerola** [comment]
It's not possible to get artifacts from the Travis CI. However, I just put version 2.0.0 to Vaadin Directory.

**Comment by xylo** [comment]
Thanks.
