### ISSUE TITLE
Grid Wrapper Exception: java.lang.IllegalArgumentException: Value is of invalid type, got java.lang.Double but double was expected

### ISSUE THREAD

**Issue by yaadyaad** [henrikerola/scaladin#64]
Hi henrikerola,

First of all, thanks a lot for your great work with scaladin, this plugin is really great!  

I have come to a runtime exception when working with Grid with the latest (today) SNAPSHOT versions of Vaadin and Scaladin.

This happens when a Scala simple Double/(Float?) types are used, Scala's String and Ints are fine. Not sure about other types yet.

To workaround this issue a java.lang.Double should be used, but this is not scalish. Here is the code:

val container = new IndexedContainer
// container.addContainerProperty("amount1", classOf[Double]) // lead to the exception
container.addContainerProperty("amount1", classOf[java.lang.Double]) // works fine

val item = container.addItem(elem.id).get
val aDouble:Double = 123.3
item.getProperty("amount1").value = aDouble

And the exception is as follows:
java.lang.IllegalArgumentException: Value is of invalid type, got java.lang.Double but double was expected
    at com.vaadin.data.util.IndexedContainer$IndexedContainerProperty.setValue(IndexedContainer.java:944)
    at vaadin.scala.Property$class.value_$eq(Property.scala:20)
    at vaadin.scala.BasicProperty.value_$eq(Property.scala:51)

Thank you,
Dmitry

**Comment by henrikerola** [comment]
This is fixed in the 3.2 branch.
