### ISSUE TITLE
There is nowhere where I could ask a question or comment

### ISSUE THREAD

**Issue by kostaskougios** [henrikerola/scaladin#8]
I was going around scaladin's repo and I can't find a way to post a question anywhere. I'm going to post it here, please let me know if you have an official place for questions.

So for scaladin v2.0.0, I am trying to create a table with the ability to filter the items based on user input. I.e. if the user types [He] in a separate text box, I then need to filter the table so that I get only the rows that contain "He". So far I did this:

```
val table = new Table {
    width = (100 percent)
    height = (100 percent)
    selectionMode = SelectionMode.Single
    immediate = true
}
val filterable = Container.filterable(
    ("x", List(
        ("AA", "A1"),
        ("BB", "B1")
    )),
    ("y", List(
        ("AA", "A2"),
        ("BB", "B2")
    )
    )
)
table.container = filterable
add(
    new Button {
        caption = "Filter"
        clickListeners += { e =>
            ???? what do I do here to filter the table???
        }
    }
)
```

**Comment by mheinola** [comment]
You probably found out the answer already but the place to ask questions is at the Vaadin forums (e.g. https://vaadin.com/forum/-/message_boards/view_message/530126 )

You could do something like this in the clickListener (did not test this):
    filterable.filterItems((i: Item) => {
              i.property("name").map(p => p.value == "Ha").getOrElse(false)
            })
